### ISSUE TITLE
unable to install wget

### ISSUE THREAD

**Issue by albert-queralto** [DoubleGremlin181/RubiksCubeGym#5]
Hi,
I am having issues trying to install the package using pip. Specifically, I get this error:

> Building wheels for collected packages: wget
>   Building wheel for wget (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [47 lines of output]
>       running bdist_wheel
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-uwcyvnup/wget_210f444a1f0847f7b37d04912ee382bb/setup.py", line 15, in <module>
>           setup(
>         File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
>           dist.run_commands()
>         File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
>           self.run_command(cmd)
>         File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 963, in run_command
>           super().run_command(command)
>         File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
>           cmd_obj.run()
>         File "/usr/local/lib/python3.10/dist-packages/wheel/bdist_wheel.py", line 360, in run
>           build_ext = self.reinitialize_command("build_ext")
>         File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 216, in reinitialize_command
>           cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
>         File "/usr/lib/python3.10/distutils/cmd.py", line 305, in reinitialize_command
>           return self.distribution.reinitialize_command(command,
>         File "/usr/lib/python3.10/distutils/dist.py", line 938, in reinitialize_command
>           command = self.get_command_obj(command_name)
>         File "/usr/lib/python3.10/distutils/dist.py", line 857, in get_command_obj
>           klass = self.get_command_class(command)
>         File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 710, in get_command_class
>           self.cmdclass[command] = cmdclass = ep.load()
>         File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>           module = import_module(match.group('module'))
>         File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>         File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 23, in <module>
>           __import__('Cython.Compiler.Main')
>         File "/usr/local/lib/python3.10/dist-packages/Cython/Compiler/Main.py", line 28, in <module>
>           from .Scanning import PyrexScanner, FileSourceDescriptor
>         File "Cython/Compiler/Scanning.py", line 1, in init Cython.Compiler.Scanning
>         File "/usr/local/lib/python3.10/dist-packages/Cython/Plex/__init__.py", line 36, in <module>
>           from .Lexicons import Lexicon, State
>         File "/usr/local/lib/python3.10/dist-packages/Cython/Plex/Lexicons.py", line 14, in <module>
>           from . import DFA
>         File "Cython/Plex/DFA.py", line 1, in init Cython.Plex.DFA
>       AttributeError: module 'Cython.Plex.Actions' has no attribute 'Method'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for wget
>   Running setup.py clean for wget
> Failed to build wget
> ERROR: Could not build wheels for wget, which is required to install pyproject.toml-based projects

I have tried installing the wget package using `pip install wget`, but the same error occurs. I have also updated pip to the latest version and the setuptools package as well, but to no avail. Is there a way to fix it?

Edit: I have tried with the pywget library which is an alternative to wget and I could install it, so it may be worth upgrading from wget to pywget.

Thank you very much.

**Comment by albert-queralto** [comment]
Hello again, I could resolve the issue by upgrading Cython using `pip install cython -U`. I hope this helps others with the same issue.
Best regards.
